Add patch config

diff --git a/.github/workflows/windows-ci.yaml b/.github/workflows/windows-ci.yaml
--- a/.github/workflows/windows-ci.yaml
+++ b/.github/workflows/windows-ci.yaml
@@ -47,23 +47,6 @@ jobs:
       shell: pwsh
       working-directory: fluent-bit\td-agent-bit-1.8.11-win64
 
-    - name: Run zip version with default config
-      # Default config prior to 1.9 is for Linux so will fail
-      continue-on-error: true
-      timeout-minutes: 1
-      run: |
-        $fluentbit=Start-Process -PassThru -NoNewWindow -FilePath "bin\fluent-bit.exe" -ArgumentList "-c", "conf\fluent-bit.conf"
-        Start-Sleep -s 15
-        if ($fluentbit.HasExited) {
-          echo "Fluent Bit exited prematurely"
-          exit 1
-        }
-        Stop-Process -Force -InputObject $fluentbit
-        Get-Process | Where-Object {$_.HasExited}
-        echo "Fluent Bit exited correctly"
-      shell: pwsh
-      working-directory: fluent-bit\td-agent-bit-1.8.11-win64
-
     - name: Run executable installer
       timeout-minutes: 5
       # Silent install accepting all defaults
@@ -78,6 +61,30 @@ jobs:
         Test-Path -Path "C:\fluent-bit\conf\parsers.conf" | Should -Be $true
         Test-Path -Path "C:\fluent-bit\conf\plugins.conf" | Should -Be $true
       shell: pwsh
+
+    - name: Patch config
+      # Default config prior to 1.9 is for Linux so will fail
+      # Only for 1.8 or earlier
+      run: |
+        wget https://raw.githubusercontent.com/fluent/fluent-bit/master/conf/fluent-bit-win32.conf -OutFile "conf\fluent-bit.conf"
+        wget https://raw.githubusercontent.com/fluent/fluent-bit/master/conf/fluent-bit-win32.conf -OutFile "C:\fluent-bit\conf\fluent-bit.conf"
+      shell: pwsh
+      working-directory: fluent-bit\td-agent-bit-1.8.11-win64
+
+    - name: Run zip version with default config
+      timeout-minutes: 1
+      run: |
+        $fluentbit=Start-Process -PassThru -NoNewWindow -FilePath "bin\fluent-bit.exe" -ArgumentList "-c", "conf\fluent-bit.conf"
+        Start-Sleep -s 15
+        if ($fluentbit.HasExited) {
+          echo "Fluent Bit exited prematurely"
+          exit 1
+        }
+        Stop-Process -Force -InputObject $fluentbit
+        Get-Process | Where-Object {$_.HasExited}
+        echo "Fluent Bit exited correctly"
+      shell: pwsh
+      working-directory: fluent-bit\td-agent-bit-1.8.11-win64
 
     - name: Run the installed version with default config
       timeout-minutes: 1
